//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureLibraryService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://asmx.libraryService.com/")]
    public partial class Book : object
    {
        
        private int IDField;
        
        private string NameField;
        
        private string AuthorNameField;
        
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AuthorName
        {
            get
            {
                return this.AuthorNameField;
            }
            set
            {
                this.AuthorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool IsAvailable
        {
            get
            {
                return this.IsAvailableField;
            }
            set
            {
                this.IsAvailableField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Token", Namespace="http://asmx.libraryService.com/")]
    public partial class Token : object
    {
        
        private string tokenField;
        
        private AzureLibraryService.PaymentInfo paymentInfoField;
        
        private string methodNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AzureLibraryService.PaymentInfo paymentInfo
        {
            get
            {
                return this.paymentInfoField;
            }
            set
            {
                this.paymentInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string methodName
        {
            get
            {
                return this.methodNameField;
            }
            set
            {
                this.methodNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentInfo", Namespace="http://asmx.libraryService.com/")]
    public partial class PaymentInfo : object
    {
        
        private string dateFromField;
        
        private string dateToField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string dateFrom
        {
            get
            {
                return this.dateFromField;
            }
            set
            {
                this.dateFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string dateTo
        {
            get
            {
                return this.dateToField;
            }
            set
            {
                this.dateToField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://asmx.libraryService.com/", ConfigurationName="AzureLibraryService.LibraryServiceSoap")]
    public interface LibraryServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.libraryService.com/GetAllBooks", ReplyAction="*")]
        System.Threading.Tasks.Task<AzureLibraryService.GetAllBooksResponse> GetAllBooksAsync(AzureLibraryService.GetAllBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.libraryService.com/GetAllBooksByName", ReplyAction="*")]
        System.Threading.Tasks.Task<AzureLibraryService.GetAllBooksByNameResponse> GetAllBooksByNameAsync(AzureLibraryService.GetAllBooksByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.libraryService.com/GetAllAvailableBooks", ReplyAction="*")]
        System.Threading.Tasks.Task<AzureLibraryService.GetAllAvailableBooksResponse> GetAllAvailableBooksAsync(AzureLibraryService.GetAllAvailableBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.libraryService.com/OrderBook", ReplyAction="*")]
        System.Threading.Tasks.Task<AzureLibraryService.OrderBookResponse> OrderBookAsync(AzureLibraryService.OrderBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.libraryService.com/ReturnBook", ReplyAction="*")]
        System.Threading.Tasks.Task<AzureLibraryService.ReturnBookResponse> ReturnBookAsync(AzureLibraryService.ReturnBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.libraryService.com/AddNewBook", ReplyAction="*")]
        System.Threading.Tasks.Task<AzureLibraryService.AddNewBookResponse> AddNewBookAsync(AzureLibraryService.AddNewBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.libraryService.com/RemoveBook", ReplyAction="*")]
        System.Threading.Tasks.Task<AzureLibraryService.RemoveBookResponse> RemoveBookAsync(AzureLibraryService.RemoveBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.libraryService.com/GetTokens", ReplyAction="*")]
        System.Threading.Tasks.Task<AzureLibraryService.GetTokensResponse> GetTokensAsync(AzureLibraryService.GetTokensRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.libraryService.com/AddToken", ReplyAction="*")]
        System.Threading.Tasks.Task<AzureLibraryService.AddTokenResponse> AddTokenAsync(AzureLibraryService.AddTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBooksRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBooks", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.GetAllBooksRequestBody Body;
        
        public GetAllBooksRequest()
        {
        }
        
        public GetAllBooksRequest(AzureLibraryService.GetAllBooksRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class GetAllBooksRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetAllBooksRequestBody()
        {
        }
        
        public GetAllBooksRequestBody(string token)
        {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBooksResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBooksResponse", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.GetAllBooksResponseBody Body;
        
        public GetAllBooksResponse()
        {
        }
        
        public GetAllBooksResponse(AzureLibraryService.GetAllBooksResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class GetAllBooksResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AzureLibraryService.Book[] GetAllBooksResult;
        
        public GetAllBooksResponseBody()
        {
        }
        
        public GetAllBooksResponseBody(AzureLibraryService.Book[] GetAllBooksResult)
        {
            this.GetAllBooksResult = GetAllBooksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBooksByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBooksByName", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.GetAllBooksByNameRequestBody Body;
        
        public GetAllBooksByNameRequest()
        {
        }
        
        public GetAllBooksByNameRequest(AzureLibraryService.GetAllBooksByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class GetAllBooksByNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public GetAllBooksByNameRequestBody()
        {
        }
        
        public GetAllBooksByNameRequestBody(string token, string name)
        {
            this.token = token;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBooksByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBooksByNameResponse", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.GetAllBooksByNameResponseBody Body;
        
        public GetAllBooksByNameResponse()
        {
        }
        
        public GetAllBooksByNameResponse(AzureLibraryService.GetAllBooksByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class GetAllBooksByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AzureLibraryService.Book[] GetAllBooksByNameResult;
        
        public GetAllBooksByNameResponseBody()
        {
        }
        
        public GetAllBooksByNameResponseBody(AzureLibraryService.Book[] GetAllBooksByNameResult)
        {
            this.GetAllBooksByNameResult = GetAllBooksByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllAvailableBooksRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllAvailableBooks", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.GetAllAvailableBooksRequestBody Body;
        
        public GetAllAvailableBooksRequest()
        {
        }
        
        public GetAllAvailableBooksRequest(AzureLibraryService.GetAllAvailableBooksRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class GetAllAvailableBooksRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetAllAvailableBooksRequestBody()
        {
        }
        
        public GetAllAvailableBooksRequestBody(string token)
        {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllAvailableBooksResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllAvailableBooksResponse", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.GetAllAvailableBooksResponseBody Body;
        
        public GetAllAvailableBooksResponse()
        {
        }
        
        public GetAllAvailableBooksResponse(AzureLibraryService.GetAllAvailableBooksResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class GetAllAvailableBooksResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AzureLibraryService.Book[] GetAllAvailableBooksResult;
        
        public GetAllAvailableBooksResponseBody()
        {
        }
        
        public GetAllAvailableBooksResponseBody(AzureLibraryService.Book[] GetAllAvailableBooksResult)
        {
            this.GetAllAvailableBooksResult = GetAllAvailableBooksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrderBookRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrderBook", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.OrderBookRequestBody Body;
        
        public OrderBookRequest()
        {
        }
        
        public OrderBookRequest(AzureLibraryService.OrderBookRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class OrderBookRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int bookId;
        
        public OrderBookRequestBody()
        {
        }
        
        public OrderBookRequestBody(string token, int bookId)
        {
            this.token = token;
            this.bookId = bookId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrderBookResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrderBookResponse", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.OrderBookResponseBody Body;
        
        public OrderBookResponse()
        {
        }
        
        public OrderBookResponse(AzureLibraryService.OrderBookResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class OrderBookResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool OrderBookResult;
        
        public OrderBookResponseBody()
        {
        }
        
        public OrderBookResponseBody(bool OrderBookResult)
        {
            this.OrderBookResult = OrderBookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnBookRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnBook", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.ReturnBookRequestBody Body;
        
        public ReturnBookRequest()
        {
        }
        
        public ReturnBookRequest(AzureLibraryService.ReturnBookRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class ReturnBookRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int bookId;
        
        public ReturnBookRequestBody()
        {
        }
        
        public ReturnBookRequestBody(string token, int bookId)
        {
            this.token = token;
            this.bookId = bookId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnBookResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnBookResponse", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.ReturnBookResponseBody Body;
        
        public ReturnBookResponse()
        {
        }
        
        public ReturnBookResponse(AzureLibraryService.ReturnBookResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class ReturnBookResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ReturnBookResult;
        
        public ReturnBookResponseBody()
        {
        }
        
        public ReturnBookResponseBody(bool ReturnBookResult)
        {
            this.ReturnBookResult = ReturnBookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewBookRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewBook", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.AddNewBookRequestBody Body;
        
        public AddNewBookRequest()
        {
        }
        
        public AddNewBookRequest(AzureLibraryService.AddNewBookRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class AddNewBookRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AzureLibraryService.Book book;
        
        public AddNewBookRequestBody()
        {
        }
        
        public AddNewBookRequestBody(string token, AzureLibraryService.Book book)
        {
            this.token = token;
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewBookResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewBookResponse", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.AddNewBookResponseBody Body;
        
        public AddNewBookResponse()
        {
        }
        
        public AddNewBookResponse(AzureLibraryService.AddNewBookResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class AddNewBookResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddNewBookResult;
        
        public AddNewBookResponseBody()
        {
        }
        
        public AddNewBookResponseBody(bool AddNewBookResult)
        {
            this.AddNewBookResult = AddNewBookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveBookRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveBook", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.RemoveBookRequestBody Body;
        
        public RemoveBookRequest()
        {
        }
        
        public RemoveBookRequest(AzureLibraryService.RemoveBookRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class RemoveBookRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int bookId;
        
        public RemoveBookRequestBody()
        {
        }
        
        public RemoveBookRequestBody(string token, int bookId)
        {
            this.token = token;
            this.bookId = bookId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveBookResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveBookResponse", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.RemoveBookResponseBody Body;
        
        public RemoveBookResponse()
        {
        }
        
        public RemoveBookResponse(AzureLibraryService.RemoveBookResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class RemoveBookResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RemoveBookResult;
        
        public RemoveBookResponseBody()
        {
        }
        
        public RemoveBookResponseBody(bool RemoveBookResult)
        {
            this.RemoveBookResult = RemoveBookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokensRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTokens", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.GetTokensRequestBody Body;
        
        public GetTokensRequest()
        {
        }
        
        public GetTokensRequest(AzureLibraryService.GetTokensRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTokensRequestBody
    {
        
        public GetTokensRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokensResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTokensResponse", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.GetTokensResponseBody Body;
        
        public GetTokensResponse()
        {
        }
        
        public GetTokensResponse(AzureLibraryService.GetTokensResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class GetTokensResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AzureLibraryService.Token[] GetTokensResult;
        
        public GetTokensResponseBody()
        {
        }
        
        public GetTokensResponseBody(AzureLibraryService.Token[] GetTokensResult)
        {
            this.GetTokensResult = GetTokensResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddToken", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.AddTokenRequestBody Body;
        
        public AddTokenRequest()
        {
        }
        
        public AddTokenRequest(AzureLibraryService.AddTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class AddTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AzureLibraryService.Token token;
        
        public AddTokenRequestBody()
        {
        }
        
        public AddTokenRequestBody(AzureLibraryService.Token token)
        {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTokenResponse", Namespace="http://asmx.libraryService.com/", Order=0)]
        public AzureLibraryService.AddTokenResponseBody Body;
        
        public AddTokenResponse()
        {
        }
        
        public AddTokenResponse(AzureLibraryService.AddTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://asmx.libraryService.com/")]
    public partial class AddTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AzureLibraryService.Token AddTokenResult;
        
        public AddTokenResponseBody()
        {
        }
        
        public AddTokenResponseBody(AzureLibraryService.Token AddTokenResult)
        {
            this.AddTokenResult = AddTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface LibraryServiceSoapChannel : AzureLibraryService.LibraryServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class LibraryServiceSoapClient : System.ServiceModel.ClientBase<AzureLibraryService.LibraryServiceSoap>, AzureLibraryService.LibraryServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LibraryServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(LibraryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), LibraryServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LibraryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LibraryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AzureLibraryService.GetAllBooksResponse> AzureLibraryService.LibraryServiceSoap.GetAllBooksAsync(AzureLibraryService.GetAllBooksRequest request)
        {
            return base.Channel.GetAllBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<AzureLibraryService.GetAllBooksResponse> GetAllBooksAsync(string token)
        {
            AzureLibraryService.GetAllBooksRequest inValue = new AzureLibraryService.GetAllBooksRequest();
            inValue.Body = new AzureLibraryService.GetAllBooksRequestBody();
            inValue.Body.token = token;
            return ((AzureLibraryService.LibraryServiceSoap)(this)).GetAllBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AzureLibraryService.GetAllBooksByNameResponse> AzureLibraryService.LibraryServiceSoap.GetAllBooksByNameAsync(AzureLibraryService.GetAllBooksByNameRequest request)
        {
            return base.Channel.GetAllBooksByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<AzureLibraryService.GetAllBooksByNameResponse> GetAllBooksByNameAsync(string token, string name)
        {
            AzureLibraryService.GetAllBooksByNameRequest inValue = new AzureLibraryService.GetAllBooksByNameRequest();
            inValue.Body = new AzureLibraryService.GetAllBooksByNameRequestBody();
            inValue.Body.token = token;
            inValue.Body.name = name;
            return ((AzureLibraryService.LibraryServiceSoap)(this)).GetAllBooksByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AzureLibraryService.GetAllAvailableBooksResponse> AzureLibraryService.LibraryServiceSoap.GetAllAvailableBooksAsync(AzureLibraryService.GetAllAvailableBooksRequest request)
        {
            return base.Channel.GetAllAvailableBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<AzureLibraryService.GetAllAvailableBooksResponse> GetAllAvailableBooksAsync(string token)
        {
            AzureLibraryService.GetAllAvailableBooksRequest inValue = new AzureLibraryService.GetAllAvailableBooksRequest();
            inValue.Body = new AzureLibraryService.GetAllAvailableBooksRequestBody();
            inValue.Body.token = token;
            return ((AzureLibraryService.LibraryServiceSoap)(this)).GetAllAvailableBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AzureLibraryService.OrderBookResponse> AzureLibraryService.LibraryServiceSoap.OrderBookAsync(AzureLibraryService.OrderBookRequest request)
        {
            return base.Channel.OrderBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<AzureLibraryService.OrderBookResponse> OrderBookAsync(string token, int bookId)
        {
            AzureLibraryService.OrderBookRequest inValue = new AzureLibraryService.OrderBookRequest();
            inValue.Body = new AzureLibraryService.OrderBookRequestBody();
            inValue.Body.token = token;
            inValue.Body.bookId = bookId;
            return ((AzureLibraryService.LibraryServiceSoap)(this)).OrderBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AzureLibraryService.ReturnBookResponse> AzureLibraryService.LibraryServiceSoap.ReturnBookAsync(AzureLibraryService.ReturnBookRequest request)
        {
            return base.Channel.ReturnBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<AzureLibraryService.ReturnBookResponse> ReturnBookAsync(string token, int bookId)
        {
            AzureLibraryService.ReturnBookRequest inValue = new AzureLibraryService.ReturnBookRequest();
            inValue.Body = new AzureLibraryService.ReturnBookRequestBody();
            inValue.Body.token = token;
            inValue.Body.bookId = bookId;
            return ((AzureLibraryService.LibraryServiceSoap)(this)).ReturnBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AzureLibraryService.AddNewBookResponse> AzureLibraryService.LibraryServiceSoap.AddNewBookAsync(AzureLibraryService.AddNewBookRequest request)
        {
            return base.Channel.AddNewBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<AzureLibraryService.AddNewBookResponse> AddNewBookAsync(string token, AzureLibraryService.Book book)
        {
            AzureLibraryService.AddNewBookRequest inValue = new AzureLibraryService.AddNewBookRequest();
            inValue.Body = new AzureLibraryService.AddNewBookRequestBody();
            inValue.Body.token = token;
            inValue.Body.book = book;
            return ((AzureLibraryService.LibraryServiceSoap)(this)).AddNewBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AzureLibraryService.RemoveBookResponse> AzureLibraryService.LibraryServiceSoap.RemoveBookAsync(AzureLibraryService.RemoveBookRequest request)
        {
            return base.Channel.RemoveBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<AzureLibraryService.RemoveBookResponse> RemoveBookAsync(string token, int bookId)
        {
            AzureLibraryService.RemoveBookRequest inValue = new AzureLibraryService.RemoveBookRequest();
            inValue.Body = new AzureLibraryService.RemoveBookRequestBody();
            inValue.Body.token = token;
            inValue.Body.bookId = bookId;
            return ((AzureLibraryService.LibraryServiceSoap)(this)).RemoveBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AzureLibraryService.GetTokensResponse> AzureLibraryService.LibraryServiceSoap.GetTokensAsync(AzureLibraryService.GetTokensRequest request)
        {
            return base.Channel.GetTokensAsync(request);
        }
        
        public System.Threading.Tasks.Task<AzureLibraryService.GetTokensResponse> GetTokensAsync()
        {
            AzureLibraryService.GetTokensRequest inValue = new AzureLibraryService.GetTokensRequest();
            inValue.Body = new AzureLibraryService.GetTokensRequestBody();
            return ((AzureLibraryService.LibraryServiceSoap)(this)).GetTokensAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AzureLibraryService.AddTokenResponse> AzureLibraryService.LibraryServiceSoap.AddTokenAsync(AzureLibraryService.AddTokenRequest request)
        {
            return base.Channel.AddTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<AzureLibraryService.AddTokenResponse> AddTokenAsync(AzureLibraryService.Token token)
        {
            AzureLibraryService.AddTokenRequest inValue = new AzureLibraryService.AddTokenRequest();
            inValue.Body = new AzureLibraryService.AddTokenRequestBody();
            inValue.Body.token = token;
            return ((AzureLibraryService.LibraryServiceSoap)(this)).AddTokenAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LibraryServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LibraryServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LibraryServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://voiteshenko-library-service.azurewebsites.net/LibraryService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LibraryServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://voiteshenko-library-service.azurewebsites.net/LibraryService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            LibraryServiceSoap,
            
            LibraryServiceSoap12,
        }
    }
}
